SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS `video` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `isdouyin` bigint(20) NOT NULL DEFAULT 1 COMMENT '是否是抖音视频',
  `name` varchar(191) NOT NULL DEFAULT '无',
  `tag` varchar(191) NOT NULL DEFAULT '无',
  `isdel` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `time` datetime NOT NULL DEFAULT current_timestamp(),
  `url` longtext NOT NULL DEFAULT '无',
  `fabulous` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `love` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `tag` (`tag`),
  KEY `isdel` (`isdel`),
  KEY `isdouyin` (`isdouyin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
